### ISSUE TITLE
Wireflow

### ISSUE THREAD

**Issue by miel775** [fdnd-task/the-client-website#11]
![Wireflow](https://github.com/user-attachments/assets/27795a21-37ff-44d4-a624-e92e6e0a3198)
Dit is de Wireflow van Bieb in Bloei.

**Comment by miel775** [comment]
Vanuit hier wordt er met het groepje besproken welke pagina iedereen zich op gaat specificeren.

**Comment by KoopReynders** [comment]
Deze aan je eigen repo toevoegen !
