### ISSUE TITLE
Prototype naar HTML

### ISSUE THREAD

**Issue by miel775** [fdnd-task/the-client-website#12]
![Wireflow](https://github.com/user-attachments/assets/04a7d267-0102-4c99-bdef-e074727303f1)

**Comment by miel775** [comment]
![Screenshot 2024-09-26 105146](https://github.com/user-attachments/assets/e60c0f37-bb5d-4699-813f-371ec03d6d22)
Brainstorming idea

**Comment by KoopReynders** [comment]
Deze aan je eigen repo toevoegen !
