### ISSUE TITLE
Prototype naar HTML

### ISSUE THREAD

**Issue by Mikiyas-hs** [fdnd-task/the-client-website#13]
![Afbeelding van WhatsApp op 2024-09-26 om 18 06 37_69856451](https://github.com/user-attachments/assets/fe89daa1-e466-4581-a420-e76e1a7b1797)
![Afbeelding van WhatsApp op 2024-09-26 om 18 06 36_2b35d977](https://github.com/user-attachments/assets/4f9f7a6b-eeda-4ace-b13b-3c50ba1193a8)
 

Dit zijn de schetsen voor de wireframe en wireflow

**Comment by KoopReynders** [comment]
Deze aan je eigen repo toevoegen!

**Comment by Mikiyas-hs** [comment]
Zal ik doen had niet door dat ik in de klassikale repo zat

Op do 26 sep. 2024 om 22:07 schreef Koop Reynders ***@***.***>
