### ISSUE TITLE
Workshop Flow layout

### ISSUE THREAD

**Issue by KoopReynders** [fdnd-task/the-client-website#7]
Over de flow van HTML
En layout modules
- Flexbox
- Positioned (eg. position: absolute)
- Grid
- Table
- Flow

https://www.joshwcomeau.com/css/understanding-layout-algorithms/

**Comment by KoopReynders** [comment]
Deze workshop heet nu _Layout Modes_. Dit gaan studenten eerst oefenen in een deeltaak en daarna toepassen in de leertaak. Bij de code/design review feedback op de layout modes.

**Comment by KoopReynders** [comment]
De workshop link nu naar de deeltaak. Zou mooi zijn als de layout modes kort staat uitgeschreven in de leertaak en van daaruit linken naar de deeltaak. 
Alsnog even doen @krijnhoetmer ?

**Comment by krijnhoetmer** [comment]
Ja, was een snelle hack, omdat ik er die ochtend achter kwam dat het verkeerd stond. Will fix!

**Comment by krijnhoetmer** [comment]
Zoiets?

**Comment by KoopReynders** [comment]
Yes. Ik heb nog wat toegevoegd. Nu istie af!
